### ISSUE TITLE
Can't get playback working on 2nd Gen Dot

### ISSUE THREAD

**Issue by xairrick** [Tyzer34/plexMusicPlayer#28]
I can't get the echo to queue up any songs or play any songs. Any ideas on what I might be doing wrong?

First request works;
"Alexa open Plex Music"
2017-05-27T13:22:29.204944+00:00 heroku[router]: at=info method=POST path="/plex" host=eric-plex-echo.herokuapp.com request_id=18265e92-9af4-4b9b-a2b1-582c3640c55d fwd="72.21.217.141" dyno=web.1 connect=0ms service=52ms status=200 bytes=473 protocol=https

but the i get an error when I ask to play something;
"Play Janet Jackson"
2017-05-27T13:22:37.750753+00:00 heroku[router]: at=info method=POST path="/plex" host=eric-plex-echo.herokuapp.com request_id=d1135be3-5047-448f-835d-d59557d79234 fwd="72.21.217.141" dyno=web.1 connect=0ms service=2122ms status=200 bytes=610 protocol=https
2017-05-27T13:22:37.930617+00:00 heroku[router]: at=info method=POST path="/plex" host=eric-plex-echo.herokuapp.com request_id=a5904f35-09a4-47ee-ab83-bd2e8786daad fwd="72.21.217.141" dyno=web.1 connect=0ms service=83ms status=500 bytes=449 protocol=https
2017-05-27T13:22:37.898075+00:00 app[web.1]: [2017-05-27 13:22:37,897] ERROR in app: Exception on /plex [POST]
2017-05-27T13:22:37.898095+00:00 app[web.1]: Traceback (most recent call last):
2017-05-27T13:22:37.898099+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
2017-05-27T13:22:37.898100+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-05-27T13:22:37.898101+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
2017-05-27T13:22:37.898102+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-05-27T13:22:37.898102+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
2017-05-27T13:22:37.898103+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-05-27T13:22:37.898104+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
2017-05-27T13:22:37.898105+00:00 app[web.1]:     raise value
2017-05-27T13:22:37.898105+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
2017-05-27T13:22:37.898106+00:00 app[web.1]:     rv = self.dispatch_request()
2017-05-27T13:22:37.898107+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
2017-05-27T13:22:37.898108+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-05-27T13:22:37.898109+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask_ask/core.py", line 499, in _flask_view_func
2017-05-27T13:22:37.898110+00:00 app[web.1]:     self._update_stream()
2017-05-27T13:22:37.898111+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask_ask/core.py", line 468, in _update_stream
2017-05-27T13:22:37.898111+00:00 app[web.1]:     fresh_stream.__dict__.update(self._from_context())
2017-05-27T13:22:37.898117+00:00 app[web.1]: TypeError: 'NoneType' object is not iterable
2017-05-27T13:22:37.898198+00:00 app[web.1]: ERROR:plexmusicplayer:Exception on /plex [POST]
2017-05-27T13:22:37.898200+00:00 app[web.1]: Traceback (most recent call last):
2017-05-27T13:22:37.898200+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
2017-05-27T13:22:37.898201+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-05-27T13:22:37.898202+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
2017-05-27T13:22:37.898203+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-05-27T13:22:37.898203+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
2017-05-27T13:22:37.898204+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-05-27T13:22:37.898205+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
2017-05-27T13:22:37.898205+00:00 app[web.1]:     raise value
2017-05-27T13:22:37.898206+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
2017-05-27T13:22:37.898207+00:00 app[web.1]:     rv = self.dispatch_request()
2017-05-27T13:22:37.898208+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
2017-05-27T13:22:37.898208+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-05-27T13:22:37.898209+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask_ask/core.py", line 499, in _flask_view_func
2017-05-27T13:22:37.898210+00:00 app[web.1]:     self._update_stream()
2017-05-27T13:22:37.898210+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask_ask/core.py", line 468, in _update_stream
2017-05-27T13:22:37.898211+00:00 app[web.1]:     fresh_stream.__dict__.update(self._from_context())
2017-05-27T13:22:37.928737+00:00 app[web.1]: TypeError: 'NoneType' object is not iterable

**Comment by xairrick** [comment]
The above error was a red herring,  I upgraded flask-ask from 0.8.4 to 0.9.3 and error stopped.

Now when I say "Alexa ask plex music to play janet jackson"  I get  "There was a problem with the requested skills response".   There are no errors in the heroku or plex logs.
